# Generated by Django 5.1.7 on 2025-03-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
