# Generated by Django 5.2 on 2025-04-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='sub_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='product_app.subsubcategory'),
        ),
        migrations.AddField(
            model_name='size',
            name='sub_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='product_app.subsubcategory'),
        ),
    ]
