# Generated by Django 5.2 on 2025-04-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
