# Generated by Django 5.2 on 2025-04-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='MPESA transaction ID. You can separate multiple IDs with commas.', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, help_text='The phone number used to pay via MPESA', max_length=20),
        ),
    ]
