# Generated by Django 5.2 on 2025-04-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('CBD', 'Nairobi CBD'), ('WESTLANDS', 'Westlands'), ('KAREN', 'Karen'), ('NGONG', 'Ngong Road')], help_text='Customer-selected pickup point.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
