# Generated by Django 5.2 on 2025-04-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('CBD', 'Nairobi CBD'), ('WESTLANDS', 'Westlands'), ('KAREN', 'Karen'), ('THIKA', 'Thika Road'), ('KITENGELA', 'Kitengela')], help_text='Customer-selected pickup point.', max_length=100),
        ),
    ]
