# Generated by Django 5.2 on 2025-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('ville', 'Ville, Bujumbura'), ('gitega', 'Gitega'), ('imenti', 'Imenti House Z39')], help_text='Customer-selected pickup point.', max_length=100),
        ),
    ]
