# Generated by Django 5.2 on 2025-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='benoti_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='benoti_transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
